import './RecommendationsPanel.css'

const PRIORITY_ORDER = { high: 0, medium: 1, low: 2 }

function formatFeatureName(name) {
  return name
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

const PRIORITY_CONFIG = {
  high: { icon: '🔴', label: 'High Priority', color: '#ef4444' },
  medium: { icon: '🟡', label: 'Medium Priority', color: '#f59e0b' },
  low: { icon: '🟢', label: 'Low Priority', color: '#22c55e' },
}

export default function RecommendationsPanel({ recommendations, aiPowered = false }) {
  const sorted = [...recommendations].sort(
    (a, b) => (PRIORITY_ORDER[a.priority] ?? 2) - (PRIORITY_ORDER[b.priority] ?? 2)
  )

  const grouped = { high: [], medium: [], low: [] }
  sorted.forEach((r) => {
    const key = r.priority in grouped ? r.priority : 'low'
    grouped[key].push(r)
  })

  if (recommendations.length === 0) {
    return (
      <div className="rec-panel card">
        <div className="rec-panel-header">
          <div className="card-title">Intervention Recommendations</div>
        </div>
        <div className="rec-empty">No recommendations at this time.</div>
      </div>
    )
  }

  return (
    <div className="rec-panel card">
      <div className="rec-panel-header">
        <div className="card-title">Intervention Recommendations</div>
        {aiPowered && (
          <div className="rec-ai-badge">
            <span className="rec-ai-badge-icon">✨</span>
            <span>Powered by OpenAI</span>
          </div>
        )}
      </div>

      {aiPowered && (
        <div className="rec-ai-notice">
          <span className="rec-ai-notice-icon">🤖</span>
          <span>These recommendations were generated by OpenAI, personalized to this patient's specific clinical values and social determinants of health.</span>
        </div>
      )}

      {(['high', 'medium', 'low']).map((priority) => {
        const items = grouped[priority]
        if (items.length === 0) return null
        const config = PRIORITY_CONFIG[priority]
        return (
          <div key={priority} className="rec-group">
            <div className={`rec-group-header badge badge-${priority}`}>
              {config.icon} {config.label}
            </div>
            <div className="rec-cards">
              {items.map((rec, idx) => (
                <div key={idx} className={`rec-card rec-card--${priority} ${aiPowered ? 'rec-card--ai' : ''}`}>
                  <div className="rec-card-factor">{formatFeatureName(rec.factor)}</div>
                  <div className="rec-card-text">{rec.recommendation}</div>
                  {aiPowered && <div className="rec-card-ai-indicator">✨ AI Generated</div>}
                </div>
              ))}
            </div>
          </div>
        )
      })}
    </div>
  )
}
