spring:
  application:
    name: frailty-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://krishnakumar176003_db_user:***REMOVED***@krishna.4r6mwfw.mongodb.net/frailtydb?appName=Krishna&retryWrites=true&w=majority}
ml:
  service:
    url: ${ML_SERVICE_URL:http://localhost:8000}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.frailty: DEBUG
